package httpapi

import (
	"crypto/sha256"
	"encoding/hex"
	"io"
	"mime"
	"net/http"
	"os"
	"sort"
	"strings"

	"github.com/aatuh/evydence/internal/app"
)

func streamedRequestFingerprint(bodyDigest string, semanticFields map[string]string) string {
	if len(semanticFields) == 0 {
		return bodyDigest
	}
	keys := make([]string, 0, len(semanticFields))
	for key := range semanticFields {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	hash := sha256.New()
	_, _ = io.WriteString(hash, bodyDigest)
	for _, key := range keys {
		_, _ = io.WriteString(hash, "\x00"+key+"\x00"+semanticFields[key])
	}
	return "sha256:" + hex.EncodeToString(hash.Sum(nil))
}

func streamRequestPayload(r *http.Request, limit int64) (app.PayloadSource, func(), error) {
	if r == nil || r.Body == nil || limit <= 0 || (r.ContentLength > limit) {
		return app.PayloadSource{}, func() {}, app.ErrValidation
	}
	temporary, err := os.CreateTemp("", "evydence-ingestion-*")
	if err != nil {
		return app.PayloadSource{}, func() {}, err
	}
	cleanup := func() {
		_ = temporary.Close()
		_ = os.Remove(temporary.Name())
	}
	if err := temporary.Chmod(0o600); err != nil {
		cleanup()
		return app.PayloadSource{}, func() {}, err
	}
	hash := sha256.New()
	count, err := io.Copy(io.MultiWriter(temporary, hash), io.LimitReader(r.Body, limit+1))
	if err != nil || count == 0 || count > limit {
		cleanup()
		return app.PayloadSource{}, func() {}, app.ErrValidation
	}
	if err := temporary.Close(); err != nil {
		cleanup()
		return app.PayloadSource{}, func() {}, err
	}
	path := temporary.Name()
	return app.PayloadSource{
		Digest: "sha256:" + hex.EncodeToString(hash.Sum(nil)),
		Size:   count,
		Open: func() (io.ReadCloser, error) {
			// #nosec G304 -- path is generated by os.CreateTemp above and is not derived from client input.
			return os.Open(path)
		},
	}, cleanup, nil
}

func requestMediaType(r *http.Request) string {
	if r == nil {
		return ""
	}
	value, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil {
		return ""
	}
	return strings.ToLower(strings.TrimSpace(value))
}

func requiredSingleHeader(r *http.Request, name string) (string, error) {
	if r == nil || len(r.Header.Values(name)) != 1 {
		return "", app.ErrValidation
	}
	value := strings.TrimSpace(r.Header.Get(name))
	if value == "" {
		return "", app.ErrValidation
	}
	return value, nil
}

func optionalSingleHeader(r *http.Request, name string) (string, error) {
	if r == nil || len(r.Header.Values(name)) > 1 {
		return "", app.ErrValidation
	}
	return strings.TrimSpace(r.Header.Get(name)), nil
}
