package httpapi

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"mime"
	"net/http"
	"os"
	"sort"
	"strings"

	"github.com/aatuh/evydence/internal/app"
	"github.com/aatuh/evydence/internal/domain"
)

type streamedUpload func(*Server, requestContext, domain.Actor, app.PayloadSource) (int, any, error)

// createStreamedEvidence spools an untrusted evidence document to a private
// temporary file while counting and hashing it. The command receives only a
// repeatable source, so it can validate and stage the document without a
// second request-sized memory allocation. The temporary file is always removed
// before the handler returns and its path is never included in an error.
func (s *Server) createStreamedEvidence(ctx requestContext, w http.ResponseWriter, r *http.Request, limit int64, semanticFields map[string]string, run streamedUpload) {
	actor, ok := s.authenticate(w, r)
	if !ok {
		return
	}
	source, cleanup, err := streamRequestPayload(r, limit)
	if err != nil {
		writeProblem(w, r, app.ErrValidation)
		return
	}
	defer cleanup()
	fingerprint := streamedRequestFingerprint(source.Digest, semanticFields)
	execute := func(requestFingerprint string) (int, any, error) {
		return s.idempotency.WithBodyDigest(ctx, actor, r.Method, r.URL.Path, r.Header.Get("Idempotency-Key"), requestFingerprint, func(commandCtx requestContext, scope commandScope) (int, any, error) {
			commandServer := *s
			scope.bind(&commandServer)
			return run(&commandServer, commandCtx, actor, source)
		})
	}
	status, response, err := execute(fingerprint)
	if errors.Is(err, app.ErrIdempotencyConflict) && fingerprint != source.Digest {
		// Before semantic metadata headers became part of native-document
		// fingerprints, retained records used the body digest alone. Retry the
		// reservation with that legacy digest only after the current fingerprint
		// conflicts. New records keep the stronger fingerprint, so a later header
		// change still conflicts instead of replaying another resource's result.
		status, response, err = execute(source.Digest)
	}
	if err != nil {
		writeProblem(w, r, err)
		return
	}
	if r.Header.Get("Idempotency-Key") != "" {
		w.Header().Set("Idempotency-Key", r.Header.Get("Idempotency-Key"))
	}
	writeData(w, status, response)
}

func streamedRequestFingerprint(bodyDigest string, semanticFields map[string]string) string {
	if len(semanticFields) == 0 {
		return bodyDigest
	}
	keys := make([]string, 0, len(semanticFields))
	for key := range semanticFields {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	hash := sha256.New()
	_, _ = io.WriteString(hash, bodyDigest)
	for _, key := range keys {
		_, _ = io.WriteString(hash, "\x00"+key+"\x00"+semanticFields[key])
	}
	return "sha256:" + hex.EncodeToString(hash.Sum(nil))
}

func streamRequestPayload(r *http.Request, limit int64) (app.PayloadSource, func(), error) {
	if r == nil || r.Body == nil || limit <= 0 || (r.ContentLength > limit) {
		return app.PayloadSource{}, func() {}, app.ErrValidation
	}
	temporary, err := os.CreateTemp("", "evydence-ingestion-*")
	if err != nil {
		return app.PayloadSource{}, func() {}, err
	}
	cleanup := func() {
		_ = temporary.Close()
		_ = os.Remove(temporary.Name())
	}
	if err := temporary.Chmod(0o600); err != nil {
		cleanup()
		return app.PayloadSource{}, func() {}, err
	}
	hash := sha256.New()
	count, err := io.Copy(io.MultiWriter(temporary, hash), io.LimitReader(r.Body, limit+1))
	if err != nil || count == 0 || count > limit {
		cleanup()
		return app.PayloadSource{}, func() {}, app.ErrValidation
	}
	if err := temporary.Close(); err != nil {
		cleanup()
		return app.PayloadSource{}, func() {}, err
	}
	path := temporary.Name()
	return app.PayloadSource{
		Digest: "sha256:" + hex.EncodeToString(hash.Sum(nil)),
		Size:   count,
		Open: func() (io.ReadCloser, error) {
			// #nosec G304 -- path is generated by os.CreateTemp above and is not derived from client input.
			return os.Open(path)
		},
	}, cleanup, nil
}

func requestMediaType(r *http.Request) string {
	if r == nil {
		return ""
	}
	value, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil {
		return ""
	}
	return strings.ToLower(strings.TrimSpace(value))
}

func requiredSingleHeader(r *http.Request, name string) (string, error) {
	if r == nil || len(r.Header.Values(name)) != 1 {
		return "", app.ErrValidation
	}
	value := strings.TrimSpace(r.Header.Get(name))
	if value == "" {
		return "", app.ErrValidation
	}
	return value, nil
}

func optionalSingleHeader(r *http.Request, name string) (string, error) {
	if r == nil || len(r.Header.Values(name)) > 1 {
		return "", app.ErrValidation
	}
	return strings.TrimSpace(r.Header.Get(name)), nil
}
