# Code generated by scripts/generate_error_catalog.py; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class ErrorCode(str, Enum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    CONFLICT = "CONFLICT"
    EVIDENCE_IMMUTABLE = "EVIDENCE_IMMUTABLE"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    IDEMPOTENCY_IN_PROGRESS = "IDEMPOTENCY_IN_PROGRESS"
    IDEMPOTENCY_REQUEST_FAILED = "IDEMPOTENCY_REQUEST_FAILED"
    COSIGN_FULL_VERIFICATION_UNAVAILABLE = "COSIGN_FULL_VERIFICATION_UNAVAILABLE"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    RATE_LIMITED = "RATE_LIMITED"
    SIGNING_PROVIDER_UNAVAILABLE = "SIGNING_PROVIDER_UNAVAILABLE"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class RetryClass(str, Enum):
    NONE = "none"
    REFRESH_AND_RETRY = "refresh_and_retry"
    IDEMPOTENCY_IN_PROGRESS = "idempotency_in_progress"
    DEPENDENCY_UNAVAILABLE = "dependency_unavailable"
    RATE_LIMITED = "rate_limited"
    TRANSIENT_PROVIDER = "transient_provider"


@dataclass(frozen=True)
class FieldViolation:
    field: str
    code: str


@dataclass(frozen=True)
class ProblemDetails:
    type: str
    title: str
    status: int
    detail: str
    code: ErrorCode
    request_id: str
    retryable: bool
    retry_class: RetryClass
    instance: str | None = None
    retry_after_seconds: int | None = None
    violations: tuple[FieldViolation, ...] = ()
