// Code generated by scripts/generate_error_catalog.py; DO NOT EDIT.
package evydence

// ErrorCode is a stable Evydence Problem Details code.
type ErrorCode string

const (
	ErrorCodeValidationFailed                  ErrorCode = "VALIDATION_FAILED"
	ErrorCodeUnauthorized                      ErrorCode = "UNAUTHORIZED"
	ErrorCodeForbidden                         ErrorCode = "FORBIDDEN"
	ErrorCodeNotFound                          ErrorCode = "NOT_FOUND"
	ErrorCodeVersionConflict                   ErrorCode = "VERSION_CONFLICT"
	ErrorCodeConflict                          ErrorCode = "CONFLICT"
	ErrorCodeEvidenceImmutable                 ErrorCode = "EVIDENCE_IMMUTABLE"
	ErrorCodeIdempotencyKeyReused              ErrorCode = "IDEMPOTENCY_KEY_REUSED"
	ErrorCodeIdempotencyInProgress             ErrorCode = "IDEMPOTENCY_IN_PROGRESS"
	ErrorCodeIdempotencyRequestFailed          ErrorCode = "IDEMPOTENCY_REQUEST_FAILED"
	ErrorCodeCosignFullVerificationUnavailable ErrorCode = "COSIGN_FULL_VERIFICATION_UNAVAILABLE"
	ErrorCodeVerificationFailed                ErrorCode = "VERIFICATION_FAILED"
	ErrorCodeRateLimited                       ErrorCode = "RATE_LIMITED"
	ErrorCodeSigningProviderUnavailable        ErrorCode = "SIGNING_PROVIDER_UNAVAILABLE"
	ErrorCodeDependencyUnavailable             ErrorCode = "DEPENDENCY_UNAVAILABLE"
	ErrorCodeInternalError                     ErrorCode = "INTERNAL_ERROR"
)

// RetryClass describes the safe action a client may take after an error.
type RetryClass string

const (
	RetryClassNone                  RetryClass = "none"
	RetryClassRefreshAndRetry       RetryClass = "refresh_and_retry"
	RetryClassIdempotencyInProgress RetryClass = "idempotency_in_progress"
	RetryClassDependencyUnavailable RetryClass = "dependency_unavailable"
	RetryClassRateLimited           RetryClass = "rate_limited"
	RetryClassTransientProvider     RetryClass = "transient_provider"
)

type FieldViolation struct {
	Field string `json:"field"`
	Code  string `json:"code"`
}

// ProblemDetails is the typed RFC 9457 error response returned by Evydence.
type ProblemDetails struct {
	Type              string           `json:"type"`
	Title             string           `json:"title"`
	Status            int              `json:"status"`
	Detail            string           `json:"detail"`
	Instance          string           `json:"instance,omitempty"`
	Code              ErrorCode        `json:"code"`
	RequestID         string           `json:"request_id"`
	Retryable         bool             `json:"retryable"`
	RetryClass        RetryClass       `json:"retry_class"`
	RetryAfterSeconds int              `json:"retry_after_seconds,omitempty"`
	Violations        []FieldViolation `json:"violations,omitempty"`
}
