package domain

const CRAReadinessTemplateVersion = "cra-readiness.v1.0.0"
const ControlCoverageTemplateVersion = "control-coverage.v1.0.0"
const CustomerPackageSchemaVersion = "customer-security-package.v2.0.0"
const CustomerPortalAccessVersion = "customer-portal-access.v1.0.0"
const EvidenceBundleImportVersion = "evidence-bundle-import.v1.0.0"
const EvidenceBundleSchemaVersion = "evidence-bundle.v1.0.0"
const EvidenceGraphSnapshotVersion = "evidence-graph-snapshot.v1.0.0"
const EvidenceSummaryVersion = "evidence-summary.v1.0.0"
const PDFReportPackageVersion = "pdf-report-package.v1.0.0"
const QuestionnaireAnswerLibraryVersion = "questionnaire-answer-library.v1.0.0"
const QuestionnaireDraftVersion = "questionnaire-draft.v1.0.0"
const QuestionnairePackageVersion = "questionnaire-package.v1.0.0"
const QuestionnaireTemplateVersion = "questionnaire-template.v1.0.0"
const RedactionProfileSchemaVersion = "redaction-profile.v1.0.0"
const ReleaseBundleSchemaVersion = "release-bundle.v1.0.0"
const ReleaseReadinessTemplateVersion = "release-readiness.v1.0.0"
const ReportTemplateSchemaVersion = "report-template.v1.0.0"
