/* Code generated by scripts/generate_error_catalog.py; DO NOT EDIT. */
export type ErrorCode =
  | "VALIDATION_FAILED"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "VERSION_CONFLICT"
  | "CONFLICT"
  | "EVIDENCE_IMMUTABLE"
  | "IDEMPOTENCY_KEY_REUSED"
  | "IDEMPOTENCY_IN_PROGRESS"
  | "IDEMPOTENCY_REQUEST_FAILED"
  | "COSIGN_FULL_VERIFICATION_UNAVAILABLE"
  | "VERIFICATION_FAILED"
  | "RATE_LIMITED"
  | "SIGNING_PROVIDER_UNAVAILABLE"
  | "DEPENDENCY_UNAVAILABLE"
  | "INTERNAL_ERROR";

export type RetryClass =
  | "none"
  | "refresh_and_retry"
  | "idempotency_in_progress"
  | "dependency_unavailable"
  | "rate_limited"
  | "transient_provider";

export type FieldViolation = {
  field: string;
  code: string;
};

export type ProblemDetails = {
  type: string;
  title: string;
  status: number;
  detail: string;
  instance?: string;
  code: ErrorCode;
  request_id: string;
  retryable: boolean;
  retry_class: RetryClass;
  retry_after_seconds?: number;
  violations?: FieldViolation[];
};
