package architecturecheck

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const fixtureModule = "github.com/aatuh/evydence"

func sourceFixture(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	files["go.mod"] = "module " + fixtureModule + "\n\ngo 1.25.0\n"
	for name, source := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(source), 0600); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func TestScanSourcesUsesGoSyntaxWithoutExecutingFixture(t *testing.T) {
	root := sourceFixture(t, map[string]string{
		"internal/release/app/service.go": `package releaseapp
import (
 alias "\x67ithub.com/aatuh/evydence/internal/adapters/postgres"
 "context"
)
// import "not/a/real/import"
const example = "import \"not/a/real/import\""
type Public interface { Read(context.Context); Write(); Embedded }
type private interface { Hidden() }
func init() { panic("inspected source must never execute") }
`,
		"internal/release/app/windows_windows.go":  "//go:build windows\n\npackage releaseapp\nimport `github.com/aatuh/evydence/internal/adapters/httpapi`\n",
		"internal/release/app/ignored_test.go":     "invalid test fixture syntax",
		"internal/release/app/testdata/ignored.go": "invalid data fixture syntax",
	})
	files, err := ScanSources(context.Background(), root, fixtureModule)
	if err != nil || len(files) != 2 {
		t.Fatalf("files=%d err=%v", len(files), err)
	}
	file := files[0]
	if file.Path != "internal/release/app/service.go" || file.Package != fixtureModule+"/internal/release/app" {
		t.Fatalf("unexpected source identity: %#v", file)
	}
	if len(file.Imports) != 2 || file.Imports[0].Path != "context" || file.Imports[1].Path != fixtureModule+"/internal/adapters/postgres" || file.Imports[1].Alias != "alias" {
		t.Fatalf("imports not structurally decoded: %#v", file.Imports)
	}
	if len(file.Interfaces) != 1 || file.Interfaces[0].Name != "Public" || file.Interfaces[0].Methods != 2 || file.Interfaces[0].Embeddings != 1 {
		t.Fatalf("public interface footprint changed: %#v", file.Interfaces)
	}
	if files[1].Imports[0].Path != fixtureModule+"/internal/adapters/httpapi" {
		t.Fatalf("build-tagged source omitted: %#v", files[1])
	}
}

func TestScanSourcesRecognizesGeneratedCodeButRetainsImports(t *testing.T) {
	root := sourceFixture(t, map[string]string{
		"internal/evidence/domain/generated.go": "// Code generated by fixture; DO NOT EDIT.\npackage evidence\nimport \"github.com/aatuh/evydence/internal/adapters/postgres\"\n" + strings.Repeat("// generated field\n", 1100),
	})
	files, err := ScanSources(context.Background(), root, fixtureModule)
	if err != nil || len(files) != 1 || !files[0].Generated || files[0].Lines != 1103 || len(files[0].Imports) != 1 {
		t.Fatalf("generated source escaped import analysis: %#v err=%v", files, err)
	}
}

func TestScanSourcesRejectsSymlinkEscapeBeforeReadingTarget(t *testing.T) {
	root := sourceFixture(t, map[string]string{"internal/app/base.go": "package app\n"})
	outside := filepath.Join(t.TempDir(), "outside.go")
	if err := os.WriteFile(outside, []byte("PRIVATE_SOURCE_CANARY invalid syntax"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "internal/app/escape.go")); err != nil {
		t.Fatal(err)
	}
	files, err := ScanSources(context.Background(), root, fixtureModule)
	if err == nil || !strings.Contains(err.Error(), "symlink") || strings.Contains(err.Error(), "PRIVATE_SOURCE_CANARY") || len(files) != 0 {
		t.Fatalf("unsafe source accepted or target leaked: files=%d err=%v", len(files), err)
	}
}

func TestScanSourcesPropagatesCancellationAndRejectsInvalidInputs(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if files, err := ScanSources(ctx, "missing", fixtureModule); !errors.Is(err, context.Canceled) || len(files) != 0 {
		t.Fatalf("cancellation lost: files=%d err=%v", len(files), err)
	}
	root := sourceFixture(t, map[string]string{"internal/app/base.go": "package app\n"})
	for _, input := range []struct {
		ctx    context.Context
		root   string
		module string
	}{{nil, root, fixtureModule}, {context.Background(), "", fixtureModule}, {context.Background(), root, "../escape"}, {context.Background(), root, ""}} {
		if _, err := ScanSources(input.ctx, input.root, input.module); err == nil {
			t.Fatal("invalid inspector input accepted")
		}
	}
}

func TestScanSourcesParseFailureDoesNotEchoSourceContents(t *testing.T) {
	root := sourceFixture(t, map[string]string{"internal/app/bad.go": "package app\nfunc PRIVATE_SOURCE_CANARY {"})
	files, err := ScanSources(context.Background(), root, fixtureModule)
	if err == nil || !strings.Contains(err.Error(), "internal/app/bad.go") || strings.Contains(err.Error(), "PRIVATE_SOURCE_CANARY") || len(files) != 0 {
		t.Fatalf("parse error leaked source or partial results: files=%d err=%v", len(files), err)
	}
}

func TestScanSourcesRejectsDirectorySymlinksAndOversizedSources(t *testing.T) {
	t.Run("directory symlink", func(t *testing.T) {
		root := sourceFixture(t, map[string]string{"internal/app/base.go": "package app\n"})
		if err := os.Symlink(t.TempDir(), filepath.Join(root, "internal/app/linked")); err != nil {
			t.Fatal(err)
		}
		if files, err := ScanSources(context.Background(), root, fixtureModule); err == nil || !strings.Contains(err.Error(), "symlink") || len(files) != 0 {
			t.Fatalf("directory link accepted: files=%d err=%v", len(files), err)
		}
	})
	t.Run("source byte limit", func(t *testing.T) {
		root := sourceFixture(t, map[string]string{"internal/app/large.go": "package app\n//" + strings.Repeat("x", 8<<20)})
		if files, err := ScanSources(context.Background(), root, fixtureModule); err == nil || !strings.Contains(err.Error(), "size limit") || len(files) != 0 {
			t.Fatalf("unbounded source accepted: files=%d err=%v", len(files), err)
		}
	})
}

func TestScanSourcesIncludesPublicAndExampleTreesButNotArtifacts(t *testing.T) {
	root := sourceFixture(t, map[string]string{
		"cmd/example/main.go":       "package main\n",
		"pkg/verifier/source.go":    "package verifier\n",
		"sdk/go/source.go":          "package sdk\n",
		"examples/client/main.go":   "package main\n",
		"tmp/source.go":             "invalid artifact syntax",
		"internal/vendor/source.go": "invalid vendored syntax",
	})
	files, err := ScanSources(context.Background(), root, fixtureModule)
	if err != nil || len(files) != 4 {
		t.Fatalf("incorrect source scope: files=%d err=%v", len(files), err)
	}
}
