#!/usr/bin/env python3
"""Generate the public Evydence error catalog and SDK error-code types.

The canonical source is internal/app/error_catalog.json, embedded by the Go
application. This generator deliberately has no network or environment input.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys
from typing import Any


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "internal" / "app" / "error_catalog.json"


def fail(message: str) -> None:
    raise SystemExit(f"error-catalog: {message}")


def load_catalog() -> list[dict[str, Any]]:
    try:
        catalog = json.loads(SOURCE.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"missing canonical catalog: {SOURCE.relative_to(ROOT)}")
    except json.JSONDecodeError as exc:
        fail(f"invalid canonical catalog: {exc}")
    if not isinstance(catalog, list) or not catalog:
        fail("canonical catalog must be a non-empty JSON array")
    seen: set[str] = set()
    for entry in catalog:
        if not isinstance(entry, dict):
            fail("catalog entry must be an object")
        code = entry.get("code")
        if not isinstance(code, str) or not code or code in seen:
            fail(f"catalog code is missing or duplicated: {code!r}")
        seen.add(code)
        if not isinstance(entry.get("status"), int) or not 400 <= entry["status"] <= 599:
            fail(f"catalog status is invalid for {code}")
        if not isinstance(entry.get("detail"), str) or not entry["detail"]:
            fail(f"catalog detail is invalid for {code}")
        if not isinstance(entry.get("retryable"), bool):
            fail(f"catalog retryable is invalid for {code}")
        if not isinstance(entry.get("retry_class"), str) or not entry["retry_class"]:
            fail(f"catalog retry_class is invalid for {code}")
        retry_after = entry.get("retry_after_seconds", 0)
        if not isinstance(retry_after, int) or retry_after < 0:
            fail(f"catalog retry_after_seconds is invalid for {code}")
    return catalog


def identifier(value: str) -> str:
    acronyms = {"api": "API", "id": "ID", "sso": "SSO", "sbom": "SBOM", "vex": "VEX", "cra": "CRA"}
    return "".join(acronyms.get(part.lower(), part.lower().capitalize()) for part in value.split("_"))


def quoted_union(values: list[str], prefix: str = "") -> str:
    return "\n".join(f'  | "{value}"' for value in values)


def render_go(catalog: list[dict[str, Any]]) -> str:
    retry_classes = list(dict.fromkeys(entry["retry_class"] for entry in catalog))
    lines = [
        "// Code generated by scripts/generate_error_catalog.py; DO NOT EDIT.",
        "package evydence",
        "",
        "// ErrorCode is a stable Evydence Problem Details code.",
        "type ErrorCode string",
        "",
        "const (",
    ]
    lines.extend(f'\tErrorCode{identifier(entry["code"])} ErrorCode = "{entry["code"]}"' for entry in catalog)
    lines.extend([")", "", "// RetryClass describes the safe action a client may take after an error.", "type RetryClass string", "", "const ("])
    lines.extend(f'\tRetryClass{identifier(value)} RetryClass = "{value}"' for value in retry_classes)
    lines.extend(
        [
            ")",
            "",
            "type FieldViolation struct {",
            '\tField string `json:"field"`',
            '\tCode  string `json:"code"`',
            "}",
            "",
            "// ProblemDetails is the typed RFC 9457 error response returned by Evydence.",
            "type ProblemDetails struct {",
            '\tType              string           `json:"type"`',
            '\tTitle             string           `json:"title"`',
            '\tStatus            int              `json:"status"`',
            '\tDetail            string           `json:"detail"`',
            '\tInstance          string           `json:"instance,omitempty"`',
            '\tCode              ErrorCode        `json:"code"`',
            '\tRequestID         string           `json:"request_id"`',
            '\tRetryable         bool             `json:"retryable"`',
            '\tRetryClass        RetryClass       `json:"retry_class"`',
            '\tRetryAfterSeconds int              `json:"retry_after_seconds,omitempty"`',
            '\tViolations        []FieldViolation `json:"violations,omitempty"`',
            "}",
            "",
        ]
    )
    raw = "\n".join(lines)
    formatted = subprocess.run(["gofmt"], input=raw, text=True, capture_output=True)
    if formatted.returncode != 0:
        fail(f"gofmt failed while generating Go SDK types: {formatted.stderr.strip()}")
    return formatted.stdout


def render_typescript(catalog: list[dict[str, Any]]) -> str:
    retry_classes = list(dict.fromkeys(entry["retry_class"] for entry in catalog))
    return "\n".join(
        [
            "/* Code generated by scripts/generate_error_catalog.py; DO NOT EDIT. */",
            "export type ErrorCode =",
            quoted_union([entry["code"] for entry in catalog]) + ";",
            "",
            "export type RetryClass =",
            quoted_union(retry_classes) + ";",
            "",
            "export type FieldViolation = {",
            "  field: string;",
            "  code: string;",
            "};",
            "",
            "export type ProblemDetails = {",
            "  type: string;",
            "  title: string;",
            "  status: number;",
            "  detail: string;",
            "  instance?: string;",
            "  code: ErrorCode;",
            "  request_id: string;",
            "  retryable: boolean;",
            "  retry_class: RetryClass;",
            "  retry_after_seconds?: number;",
            "  violations?: FieldViolation[];",
            "};",
            "",
        ]
    )


def render_python(catalog: list[dict[str, Any]]) -> str:
    retry_classes = list(dict.fromkeys(entry["retry_class"] for entry in catalog))
    lines = [
        "# Code generated by scripts/generate_error_catalog.py; DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from enum import Enum",
        "",
        "",
        "class ErrorCode(str, Enum):",
    ]
    lines.extend(f'    {entry["code"]} = "{entry["code"]}"' for entry in catalog)
    lines.extend(["", "", "class RetryClass(str, Enum):"])
    lines.extend(f'    {value.upper()} = "{value}"' for value in retry_classes)
    lines.extend(
        [
            "",
            "",
            "@dataclass(frozen=True)",
            "class FieldViolation:",
            "    field: str",
            "    code: str",
            "",
            "",
            "@dataclass(frozen=True)",
            "class ProblemDetails:",
            "    type: str",
            "    title: str",
            "    status: int",
            "    detail: str",
            "    code: ErrorCode",
            "    request_id: str",
            "    retryable: bool",
            "    retry_class: RetryClass",
            "    instance: str | None = None",
            "    retry_after_seconds: int | None = None",
            "    violations: tuple[FieldViolation, ...] = ()",
            "",
        ]
    )
    return "\n".join(lines)


def render_docs(catalog: list[dict[str, Any]]) -> str:
    lines = [
        "# API Error Codes",
        "",
        "<!-- Code generated by scripts/generate_error_catalog.py; DO NOT EDIT. -->",
        "",
        "Evydence errors use RFC 9457 Problem Details. `code` and `retry_class` are stable machine-readable values; clients should switch on those fields rather than the human-readable `title` or `detail`.",
        "",
        "Every error includes `request_id`. Validation responses may add safe JSON Pointer `violations` with a `field` and a machine-readable `code`; they never contain raw parser, database, provider, or object-store messages.",
        "",
        "| Code | HTTP status | Retryable | Retry class | Retry-After | Safe detail |",
        "| --- | ---: | :---: | --- | ---: | --- |",
    ]
    for entry in catalog:
        retry_after = str(entry.get("retry_after_seconds", ""))
        lines.append(
            f'| `{entry["code"]}` | {entry["status"]} | {"yes" if entry["retryable"] else "no"} | `{entry["retry_class"]}` | {retry_after} | {entry["detail"]} |'
        )
    lines.extend(
        [
            "",
            "`Retry-After` is emitted when the catalog supplies a positive retry interval. A retry class can remain `dependency_unavailable` without being retryable when operator configuration, rather than elapsed time, is required.",
            "",
        ]
    )
    return "\n".join(lines)


def render_sdk_json(catalog: list[dict[str, Any]]) -> str:
    return json.dumps({"version": 1, "errors": catalog}, indent=2, sort_keys=True) + "\n"


def outputs(catalog: list[dict[str, Any]]) -> dict[pathlib.Path, str]:
    return {
        ROOT / "docs" / "reference" / "error-codes.md": render_docs(catalog),
        ROOT / "sdk" / "error-codes.json": render_sdk_json(catalog),
        ROOT / "sdk" / "go" / "evydence" / "error_codes.go": render_go(catalog),
        ROOT / "sdk" / "typescript" / "error_codes.ts": render_typescript(catalog),
        ROOT / "sdk" / "python" / "error_codes.py": render_python(catalog),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write generated artifacts")
    args = parser.parse_args()
    stale: list[str] = []
    for path, expected in outputs(load_catalog()).items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual == expected:
            continue
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
        else:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        fail("generated artifacts are out of date; run scripts/generate_error_catalog.py --write: " + ", ".join(stale))
    print(f"error-catalog: validated {len(load_catalog())} codes")


if __name__ == "__main__":
    main()
