#!/usr/bin/env python3
"""Generate and validate Evydence persistence decomposition inventory."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
APP_ROOT = REPO_ROOT / "internal" / "app"
OUTPUT = REPO_ROOT / "docs" / "reference" / "persistence-decomposition.md"

FUNC_RE = re.compile(r"^func\s+(?:\([^)]*\)\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*\(")


@dataclass(frozen=True)
class PersistCall:
    file: str
    function: str
    call: str


FAMILY_BY_FILE = {
    "builds.go": "build provenance",
    "controls.go": "controls",
    "enterprise.go": "enterprise identity and retention",
    "future_extensions.go": "future extensions and generated reports",
    "governance_packages.go": "governance, packages, and package reports",
    "identity_service.go": "identity",
    "implementation_increments.go": "release extensions, source, and deployment",
    "integrity_runtime.go": "integrity and operations",
    "ledger.go": "release ledger and signing",
    "risk_workflows.go": "risk and security workflows",
    "state.go": "persistence helpers",
    "vex.go": "VEX and vulnerability decisions",
}


def collect_calls() -> list[PersistCall]:
    calls: list[PersistCall] = []
    for path in sorted(APP_ROOT.glob("*.go")):
        if path.name.endswith("_test.go") or path.name == "state.go":
            continue
        current = "package-scope"
        for line in path.read_text(encoding="utf-8").splitlines():
            match = FUNC_RE.match(line)
            if match:
                current = match.group(1)
                continue
            for call in (
                "persistCriticalLocked",
                "persistReleaseLedgerLocked",
                "persistReleaseLedgerWithOutboxLocked",
                "persistLocked",
            ):
                if f".{call}(ctx" in line or f" {call}(ctx" in line:
                    calls.append(PersistCall(path.name, current, call))
    return calls


def render_table(calls: list[PersistCall]) -> list[str]:
    if not calls:
        return ["| Family | File | Function | Call |", "| --- | --- | --- | --- |", "| none | none | none | none |"]
    rows = ["| Family | File | Function | Call |", "| --- | --- | --- | --- |"]
    for call in sorted(calls, key=lambda c: (FAMILY_BY_FILE.get(c.file, c.file), c.file, c.function, c.call)):
        rows.append(
            "| "
            + " | ".join(
                [
                    FAMILY_BY_FILE.get(call.file, "unclassified"),
                    f"`internal/app/{call.file}`",
                    f"`{call.function}`",
                    f"`{call.call}`",
                ]
            )
            + " |"
        )
    return rows


def render(calls: list[PersistCall]) -> str:
    critical = [c for c in calls if c.call == "persistCriticalLocked"]
    release = [c for c in calls if c.call in {"persistReleaseLedgerLocked", "persistReleaseLedgerWithOutboxLocked"}]
    broad = [c for c in calls if c.call == "persistLocked"]
    lines: list[str] = [
        "# Persistence Decomposition Inventory",
        "",
        "This reference is generated by `scripts/persistence_decomposition_inventory.py`.",
        "Update it with `scripts/persistence_decomposition_inventory.py --write` after persistence call sites change.",
        "",
        "Purpose: keep the production persistence story inspectable while Evydence continues splitting the large application ledger into focused repository paths.",
        "",
        "## Current Production Contract",
        "",
        "- Production PostgreSQL startup uses relational-only reconstruction.",
        "- Production writes do not create or update the compatibility `ledger_state` snapshot row.",
        "- `persistCriticalLocked` writes high-risk identity, key, idempotency, signing, verification, bundle, provider-verification, decision, audit-chain, and outbox state through focused PostgreSQL transactions when the store supports them.",
        "- `persistReleaseLedgerLocked` and `persistReleaseLedgerWithOutboxLocked` write release-ledger and evidence-core state through focused PostgreSQL transactions when the store supports them.",
        "- Remaining direct `persistLocked` call sites use `SaveRelationalState` with the PostgreSQL store, not `SaveState`; compatibility `SaveState` remains for memory/local/demo/import paths.",
        "- One API writer replica remains the supported production candidate topology until every write family has focused repository paths or a reviewed optimistic-concurrency design.",
        "",
        "## Focused Critical Mutations",
        "",
        *render_table(critical),
        "",
        "## Focused Release And Evidence Mutations",
        "",
        *render_table(release),
        "",
        "## Remaining Broad Relational-State Mutations",
        "",
        *render_table(broad),
        "",
        "## Next Decomposition Order",
        "",
        "1. Package and report writes: customer package access counters, generated HTML/PDF/report rows, evidence bundles, questionnaire outputs, and customer-facing access records.",
        "2. Controls and governance writes: frameworks, controls, control evidence, waivers, approvals, and custom policies.",
        "3. Build/source/deployment writes: build runs, attestations, source snapshots, release candidates, image/signature records, and deployment events.",
        "4. Integrity and operations writes: signing providers, signing operations, Merkle batches, transparency checkpoints, retention policies, backup manifests, and verification receipts.",
        "5. Future-extension rows: marketplace collectors, public transparency items, graph snapshots, SaaS profile records, PDF/anomaly reports, and AI/questionnaire draft artifacts.",
        "",
        "## Regression Checks",
        "",
        "- `go test ./internal/app -run TestRelationalStateStore` proves representative broad relational-state families avoid aggregate `SaveState` when `SaveRelationalState` is available.",
        "- `go test ./internal/adapters/postgres -run 'TestApply(Critical|ReleaseLedger)Mutation'` proves focused mutations write relational tables and avoid the compatibility snapshot row.",
        "- `make persistence-decomposition-check` regenerates this inventory and fails when the documented call-site map drifts.",
        "",
        "## Limitations",
        "",
        "This inventory is a repository-local decomposition map. It is not evidence of legal compliance, certification, complete operational hardening, or multi-writer API safety.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write generated inventory to docs/reference/persistence-decomposition.md")
    parser.add_argument("--check", action="store_true", help="fail if the generated inventory differs from the committed file")
    args = parser.parse_args()
    body = render(collect_calls())
    if args.write:
        OUTPUT.write_text(body, encoding="utf-8")
        return 0
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != body:
            diff = difflib.unified_diff(
                current.splitlines(),
                body.splitlines(),
                fromfile=str(OUTPUT),
                tofile="generated",
                lineterm="",
            )
            print("\n".join(diff), file=sys.stderr)
            return 1
        return 0
    print(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
